<<<<<<< HEAD
# Generated by Django 3.0.2 on 2020-02-24 04:02

from django.db import migrations, models
=======
<<<<<<< HEAD
# Generated by Django 3.0.2 on 2020-02-26 02:21
=======
# Generated by Django 3.0.2 on 2020-02-26 03:00
>>>>>>> dev

from django.conf import settings
from django.db import migrations, models
<<<<<<< HEAD
import phone_field.models
=======
import django.db.models.deletion
>>>>>>> dev
>>>>>>> dev


class Migration(migrations.Migration):

    initial = True

    dependencies = [
<<<<<<< HEAD
=======
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
>>>>>>> dev
    ]

    operations = [
        migrations.CreateModel(
<<<<<<< HEAD
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Question_text', models.CharField(max_length=200)),
                ('Class_text', models.CharField(max_length=200)),
                ('Comments_text', models.CharField(max_length=10000)),
                ('File_upload', models.ImageField(upload_to='')),
=======
            name='Tutee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tutee_ID', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Tutor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tutor_ID', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
<<<<<<< HEAD
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userid', models.CharField(max_length=300)),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('image', models.CharField(max_length=300)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('formCompleted', models.BooleanField(default=False)),
                ('firstName', models.CharField(max_length=10)),
                ('lastName', models.CharField(max_length=10)),
                ('phoneNumber', phone_field.models.PhoneField(blank=True, help_text='Mobile phone number', max_length=31)),
                ('computingID', models.CharField(max_length=7)),
                ('schoolYear', models.IntegerField()),
                ('classes', models.CharField(max_length=200)),
                ('gpa', models.FloatField()),
                ('bio', models.TextField(max_length=300)),
=======
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(blank=True, max_length=30)),
                ('birthdate', models.DateField(blank=True, null=True)),
                ('role', models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Student'), (2, 'Teacher'), (3, 'Supervisor')], null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
>>>>>>> dev
>>>>>>> dev
            ],
        ),
    ]
