# Generated by Django 3.0.2 on 2020-04-24 01:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='File_upload',
        ),
    ]
