# Generated by Django 3.0.2 on 2020-03-01 00:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='ID',
        ),
    ]
