# Generated by Django 3.0.2 on 2020-02-24 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='People',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=200)),
                ('name', models.CharField(max_length=200)),
                ('class_id', models.CharField(max_length=200)),
                ('rating', models.CharField(max_length=200)),
                ('status', models.BooleanField()),
            ],
        ),
    ]
