# Generated by Django 3.0.2 on 2020-03-31 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20200327_1535'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='Class_text',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='question',
            name='Comments_text',
            field=models.CharField(default='', max_length=10000),
        ),
        migrations.AlterField(
            model_name='question',
            name='Question_text',
            field=models.CharField(default='', max_length=200),
        ),
    ]
