# Generated by Django 3.0.2 on 2020-03-31 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20200331_1248'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='connection',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
