# Generated by Django 3.0.2 on 2020-03-01 01:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20200229_1957'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='latitude',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='profile',
            name='longitude',
            field=models.FloatField(),
        ),
    ]
