# Generated by Django 3.0.2 on 2020-04-11 02:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_tutee_ratingpage'),
    ]

    operations = [
        migrations.AddField(
            model_name='tutee',
            name='asked',
            field=models.BooleanField(default=False),
        ),
    ]
