# Generated by Django 3.0.2 on 2020-04-01 03:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_profile_tutor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='tutor',
        ),
    ]
