# Generated by Django 3.0.2 on 2020-04-07 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_question_person'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='asker',
            field=models.CharField(default='', max_length=10000),
        ),
    ]
