# Generated by Django 3.0.2 on 2020-04-07 23:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_question_person'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='asker',
        ),
    ]
