# Generated by Django 3.0.2 on 2020-04-08 00:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_remove_question_asker'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='asker',
            field=models.CharField(default='', max_length=10),
        ),
    ]
